### ISSUE TITLE
PassiveArmor stacking using Period in effect

### ISSUE THREAD

**Issue by Zod20** [tranek/GASDocumentation#15]
Hey, just wanted to let you know that in GE_PassiveArmor you can set the period in the effect itself to achieve the same task that your ability is doing. For example if you put period as 0.25 s then every 0.25 s your effect will be applied automatically. This will mean you don't have to do the task wait delay in the GA_PassiveArmor and just wait and listen for incoming damage.

You might add a section for this since the 'period' (works only in infinite and duration gameplay effects) provides a good way to do health regen, mana regen, health potions and any periodic effects that repeatedly change a attribute over time.

Love the documentation by the way :D

**Comment by acxsasx** [comment]
But it’s not the same effect. In situations where you only want the armor to increase when you take damage you don’t want it to increase every period of time. It’s the damage that’s triggering the effect. So this is a good example of where you’re waiting for some other event to trigger a game play affect.

**Comment by acxsasx** [comment]
Also this is a good place to discuss this on the discord app in unreal slackers.  This area is more for code issues.

**Comment by Zod20** [comment]
![image](https://user-images.githubusercontent.com/13594090/73594788-78af5480-4509-11ea-8e8c-39041ba1167e.png)

I was talking about the passive armor ability in the sample project. In the ability as you can see in the screenshot, a stack is added every X seconds. The GE armor class itself can do this type of stacking every X seconds with the 'period'. Also there are some other code within the ability that manually manages the stacks. These can be automated as well within the effect stack policy.

**Comment by tranek** [comment]
Hi and thanks for the suggestions.

Using a periodic stacking GE to add to the stacks is a valid approach. I believe that you will still need additional logic external to the GE to add/remove a new GameplayTag when max stacks has been reached that is on the GE's Ignore `Ongoing Tag Requirements`. I don't think that there's a built-in way for a periodic stacking GE to pause itself when max stacks has been reached. If you know of one, please let me know. This will be necessary to use the periodic's `Periodic Inhibition Policy` to reset the timer when the inhibition (Ignore `Ongoing Tag Requirements`) is removed. Otherwise the period timer will constantly be ticking and trying to apply a new stack at max. This could run into a scenario where you lose a stack but the timer could immediately finish granting a new stack which I did not want in this ability's design. This project was created in 4.22, before GE's had `EGameplayEffectPeriodInhibitionRemovedPolicy` which was added in 4.23 which is why I chose not to use a periodic GE at the time.

The benefit of your suggestion would be one less AbilityTask (the WaitDelay), but we would still need to listen for stack change to add and remove the new max stacks GameplayTag. I'm not worried about hitting the max limit of AbilityTasks (1000) in this project and the performance impact of the WaitDelay task is negligible.

I won't be changing the Sample Project since this isn't a necessary change, but it's a good suggestion and I may use it in future sample projects.

I already have a small section that briefly describes periodic effects. While it doesn't explicitly give many usage examples, the Sample Project does use them for things like health regen. I think eventually I'll expand upon them and maybe even break them into their own subsection, but that is not a high priority and I think this brief description is good enough for now.

>Duration and Infinite GameplayEffects have the option of applying Periodic Effects that apply its Modifiers and Executions every X seconds as defined by its Period. Periodic Effects are treated as Instant GameplayEffects when it comes to changing the Attribute's BaseValue and Executing GameplayCues. These are useful for damage over time (DOT) type effects. Note: Periodic Effects cannot be predicted.
