### ISSUE TITLE
Is calling EndTask() on AbilityTasks like WaitTargetData still necessary?

### ISSUE THREAD

**Issue by y4ure** [tranek/GASDocumentation#40]
From the docs under 4.7.3:
> Some AbilityTasks don't automatically end when the GameplayAbility ends like WaitTargetData. These should be manually ended in the GameplayAbility's OnEndAbility if they're still running (WaitTargetData naturally ends when the user presses Confirm or Cancel inputs).

WaitTargetData tasks seems to be ending automatically whether I'm ending or cancelling/interrupting the gameplay ability.
I can't see anything obvious that is preventing these ability tasks to end when the ability ends.
Have I missed something or has this changed in newer engine versions?
I'm on 4.25.

**Comment by Bit-Rot** [comment]
Gave it a quick look just now.  I've pasted some relevant code below.

To summarize, when an ability ends, we call TaskOwnerEnded() on each active task.  TaskOwnerEnded() is basically the same logic as EndTask() - both call OnDestroy, but one passes in a value of true, the other false.  The base definition of OnDestroy doesn't use this boolean at all (presumably it's for children to use) - and since there's nothing that stands out to me in WaitTargetData's OnDestroy definition, I think @y4ure is correct here, and that WaitTargetData is ending just like any other ability on gameplay ability end.

GameplayAbility.cpp:633 (EndTask())
```
		// Tell all our tasks that we are finished and they should cleanup
		for (int32 TaskIdx = ActiveTasks.Num() - 1; TaskIdx >= 0 && ActiveTasks.Num() > 0; --TaskIdx)
		{
			UGameplayTask* Task = ActiveTasks[TaskIdx];
			if (Task)
			{
				Task->TaskOwnerEnded();
			}
		}
```

GameplayTask.cpp:140 (TaskOwnerEnded())
```
void UGameplayTask::TaskOwnerEnded()
{
	UE_VLOG(GetGameplayTasksComponent(), LogGameplayTasks, Verbose
		, TEXT("%s TaskOwnerEnded called, current State: %s")
		, *GetName(), *GetTaskStateName());

	if (TaskState != EGameplayTaskState::Finished)
	{
		bOwnerFinished = true;
		if (IsPendingKill() == false)
		{
			OnDestroy(true);
		}
		else
		{
			// mark as finished, just to be on the safe side 
			TaskState = EGameplayTaskState::Finished;
		}
	}
}
```

GameplayTask.cpp:161 (EndTask())
```
void UGameplayTask::EndTask()
{
	UE_VLOG(GetGameplayTasksComponent(), LogGameplayTasks, Verbose
		, TEXT("%s EndTask called, current State: %s")
		, *GetName(), *GetTaskStateName());

	if (TaskState != EGameplayTaskState::Finished)
	{
		if (IsPendingKill() == false)
		{
			OnDestroy(false);
		}
		else
		{
			// mark as finished, just to be on the safe side 
			TaskState = EGameplayTaskState::Finished;
		}
	}
}
```

GameplayTask:202 (OnDestroy())
```
void UGameplayTask::OnDestroy(bool bInOwnerFinished)
{
	ensure(TaskState != EGameplayTaskState::Finished && !IsPendingKill());
	TaskState = EGameplayTaskState::Finished;

	if (UGameplayTasksComponent* TasksPtr = TasksComponent.Get())
	{
		TasksPtr->OnGameplayTaskDeactivated(*this);
	}

	MarkPendingKill();
}
```

**Comment by tranek** [comment]
Looks like you guys are correct that this is no longer the case. When I first built this project, the Meteor ability's WaitTargetData AbilityTask would not end when the player was stunned and the solution was to manually end the task on ability end. That no longer seems to be the case. I have updated the project and the README to reflect this.

Thank you two for bringing this up and checking the source!
