### ISSUE TITLE
Why is Addition Used in "4.5.12.1.2 Backing Data Attribute Calculation Modifier"?

### ISSUE THREAD

**Issue by GuyPaddock** [tranek/GASDocumentation#71]
In both section [4.5.12.1.2 Backing Data Attribute Calculation Modifier](https://github.com/tranek/GASDocumentation#451212-backing-data-attribute-calculation-modifier) and in the Epic Action RPG sample, damage GEs snapshot the _source_ damage before adding the weapon damage to it. Why?

* Is the "source" in this context the character who initiated the damage or is it the ASC on which the damage GE is being executed?
* If the "source" is the character who initiated the damage, wouldn't this mean that if a character who just received damage ("character A") attacks another character ("character B"), character A's injury/damage would add to damage being inflicted on character B?

**Comment by tranek** [comment]
Hey that's a great question. Source is the initiating character. I don't know why ActionRPG went with Source. I think I just copied it and never put any thought into it. In the basic scenario, it doesn't matter. The Damage attribute gets reset to 0 in the [AttributeSet](https://github.com/tranek/GASDocumentation/blob/master/Source/GASDocumentation/Private/Characters/Abilities/AttributeSets/GDAttributeSetBase.cpp#L110) so it will always be zeroed out before using it and we'll never run into the scenario that you described. Even though we're "capturing" it at the time the GE Spec is created, which could happen any time before the GE Spec is applied, it will always be zero because we're immediately zeroing it out in the AttributeSet. I think that you would be fine setting it as Target and not captured.

Also look into [temporary variables](https://github.com/tranek/GASDocumentation#concepts-ge-ec-senddata-backingdatatempvariable), however those can only be used with ExecutionCalculations.

**Comment by GuyPaddock** [comment]
Yeah, I was aware of how the damage gets reset and I was aware of temporary variables; I was mainly interested in confirming that my hypothesis about the subtle bug was correct. With the way Epic handles it, if anything causes the damage not to be reset to zero (e.g. if the attribute set did something odd like carrying a reduced amount of damage forward to the next frame, etc.), then the source damage affects the damage on the target.
