### ISSUE TITLE
In UE5.1 preview: SMPAbilityTask_PlayMontageAndWaitForEvent.cpp(179): error C2678: binary '!': no operator found

### ISSUE THREAD

**Issue by hamar02** [tranek/GASDocumentation#89]
C:\Perforce\...\Source\....\SMPAbilityTask_PlayMontageAndWaitForEvent.cpp(179): error C2678: binary '!': no operator found which takes a left-hand operand of type 'TWeakObjectPtr<UAbilitySystemComponent,FWeakObjectPtr>' (or there is no acceptable conversion)

**Comment by xSliver** [comment]
You have to add ".IsValid()" where you access your AbilitySystemComponent. Looks like EPIC changed the type to 'TWeakObjectPtr' instead of a regular pointer (actually I dont have a clue since i'm a beginner, the following fixed it for me). 

'if (AbilitySystemComponent.IsValid() && Ability)' instead of 'if (AbilitySystemComponent && Ability)'

**Comment by tranek** [comment]
I won't be able to check on it for a few weeks as I don't have access to a PC right now.

**Comment by tranek** [comment]
@xSliver Is correct. All instances of this are fixed now in the 5.1 and master branches.
